services:
    cgonser.swift_mailer.spool.db_s3:
        class: Cgonser\SwiftMailerDatabaseS3SpoolBundle\Spool\DatabaseS3Spool
        arguments:
            - "%cgonser_swift_mailer_database_s3_spool.s3%"
            - "%cgonser_swift_mailer_database_s3_spool.entity_class%"
            - "@doctrine"
            - "@enqueue.transport.context"
            - "@cgonser.swift_mailer.transport_chain"
            - "@doctrine.orm.default_second_level_cache.region_cache_driver"
            - "@logger"
        calls:
         - ['setDisableDelivery', ['%cgonser_swift_mailer_database_s3_spool.delivery_disable%']]
         - ['setDeduplicationPeriod', ['%cgonser_swift_mailer_database_s3_spool.deduplication_period%']]
    swiftmailer.spool.db_s3:
        alias: cgonser.swift_mailer.spool.db_s3
    swiftmailer.mailer.default.spool.db_s3:
        alias: cgonser.swift_mailer.spool.db_s3
    Cgonser\SwiftMailerDatabaseS3SpoolBundle\Repository\MailQueueTransportRepository:
        class: Cgonser\SwiftMailerDatabaseS3SpoolBundle\Repository\MailQueueTransportRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Cgonser\SwiftMailerDatabaseS3SpoolBundle\Entity\MailQueueTransport
    cgonser.swift_mailer.transport_chain:
        class: Cgonser\SwiftMailerDatabaseS3SpoolBundle\Transport\TransportChain
        autowire: true
        shared: true
        lazy: true
