<?php

namespace Cgonser\SwiftMailerDatabaseS3SpoolBundle\Repository;

/**
 * MailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFailedMessages($limit = null){

        $qb = $this->createQueryBuilder('m');
        $qb->andWhere($qb->expr()->isNull('m.sentAt'))
           ->andWhere($qb->expr()->isNotNull('m.startedAt'))
           ->andWhere($qb->expr()->isNotNull('m.errorMessage'))
           ->addOrderBy('m.startedAt', 'ASC')
        ;

        if(!empty($limit)){
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }


}
